### PR TITLE
Update mlua 10.0 and deprecate rlua

### PR DESCRIPTION
**Pull request by jj136975**
MLua just got an update to version 10.0 that fully remove `'lua` lifetime and much more.
RLua version 20.0 is now deprecated and merged into MLua (rlua re-export mlua modules).

Maybe it's a good time to bump tealr version

### CODE REVIEW

**Comment by lenscas** [comment]
The title says "deprecate rlua" but it seems to be entirely removed instead?

**Comment by jj136975** [comment]
I've tried upgrading only mlua to 10.0 and let rlua to 19.0 but the implementation is way too different now.
Maybe you can make a version with some deprecation warning and remove rlua entirely with a new major like tealr 0.10.0 (it will follow mlua major)

**Comment by lenscas** [comment]
Fair. I will look at it more during the weekend.

**Comment by lenscas** [comment]
Didn't have nearly as much time as I wanted. So, didn't really get to it.

One question though: Can it be made such that the old path is still valid? I have a private version of tealr where I play with piccolo support. So, eventually (hopefully at least) the `tealr::mlu::*` path will come back anyway and having it also reduces the amount of churn that needs to happen now.

I am fine with the movement of all the code itself though. It will probably be _quite_ a while before the piccolo backend can be merged proper and until then there is no reason to pretend there is another backend.

**Comment by jj136975** [comment]
I don't realy understand your question. Maybe change the destination branch of this PR to a new one, then apply any changes you want and submite a new PR.
Alternatively you can write a PR on my fork.

**Comment by lenscas** [comment]
Disregard my last comment. No idea why I thought you got rid of the `mlu` module.

Anyway, managed to look better at the code. Fixed the problems caught in CI and ported tealsql over to it. Still need to make a couple of changes and then I am going to see if tealr_doc_gen works with the new version.


Assuming everything works then I can do a new release tomorrow.

**Comment by jj136975** [comment]
[like]  Matthieu Daumas reacted to your message:
________________________________

**Comment by lenscas** [comment]
Thank you for your help in getting this done! :tada:

**Pull request merged**
